### PR TITLE
added student, drinks tables to database. Also added seeds for these

### PR DESCRIPTION
**Pull request by ByHT**
Added following table and seed to 

- students

- drinks

- orders

### CODE REVIEW

**Comment by ByHT** [comment]
Not sure if Orders are right.
Got a odd feeling about it

**Comment by SimonNord** [comment]
Gick det att köra migrate och seeda till alla?

**Comment by ByHT** [comment]
Gick bra att migrate och seed,  får visa sen

**Comment by SimonNord** [comment]
lägg till en paid column i orders tabellen. Sen är vi good to go! bra jobbat 😃 👍

**Comment by SimonNord** [comment]
btw!
fixes #3 right?

**Comment by ByHT** [comment]
added history table,
removed order_Id foreign key from history table.
added seeds for history

**Review by SimonNord — APPROVED** [review]

**Comment by SimonNord** [comment]
Nu fungerar det utmärkt!

**Pull request merged**
